// src/data/members.ts の写し。片方だけ直すとずれる。
// グループ名は src/data/groups.ts（HELLO_GROUPS の name）の写し。こちらも片方だけ直すとずれる。
// 受付係（functions/）は src/ を読めないので、名前とグループだけをここに持つ（色・愛称は判定に使わないので写さない）。
// 愛称（nicks）は普通の言葉と重なるので、判定には使わない。

export interface RosterMember {
  name: string;
  group: string;
}

export const CROSSWORD_MEMBERS: readonly RosterMember[] = [
  { name: "弓桁朱琴", group: "モーニング娘。'26" },
  { name: "牧野真莉愛", group: "モーニング娘。'26" },
  { name: "小田さくら", group: "モーニング娘。'26" },
  { name: "野中美希", group: "モーニング娘。'26" },
  { name: "井上春華", group: "モーニング娘。'26" },
  { name: "山﨑愛生", group: "モーニング娘。'26" },
  { name: "櫻井梨央", group: "モーニング娘。'26" },
  { name: "岡村ほまれ", group: "モーニング娘。'26" },
  { name: "杉原明紗", group: "モーニング娘。'26" },
  { name: "橋迫鈴", group: "アンジュルム" },
  { name: "下井谷幸穂", group: "アンジュルム" },
  { name: "為永幸音", group: "アンジュルム" },
  { name: "後藤花", group: "アンジュルム" },
  { name: "平山遊季", group: "アンジュルム" },
  { name: "川名凜", group: "アンジュルム" },
  { name: "松本わかな", group: "アンジュルム" },
  { name: "伊勢鈴蘭", group: "アンジュルム" },
  { name: "長野桃羽", group: "アンジュルム" },
  { name: "川嶋美楓", group: "Juice=Juice" },
  { name: "工藤由愛", group: "Juice=Juice" },
  { name: "入江里咲", group: "Juice=Juice" },
  { name: "石山咲良", group: "Juice=Juice" },
  { name: "松永里愛", group: "Juice=Juice" },
  { name: "有澤一華", group: "Juice=Juice" },
  { name: "遠藤彩加里", group: "Juice=Juice" },
  { name: "林仁愛", group: "Juice=Juice" },
  { name: "井上玲音", group: "Juice=Juice" },
  { name: "江端妃咲", group: "Juice=Juice" },
  { name: "段原瑠々", group: "Juice=Juice" },
  { name: "秋山眞緒", group: "つばきファクトリー" },
  { name: "小野田紗栞", group: "つばきファクトリー" },
  { name: "谷本安美", group: "つばきファクトリー" },
  { name: "河西結心", group: "つばきファクトリー" },
  { name: "福田真琳", group: "つばきファクトリー" },
  { name: "小野瑞歩", group: "つばきファクトリー" },
  { name: "石井泉羽", group: "つばきファクトリー" },
  { name: "豫風瑠乃", group: "つばきファクトリー" },
  { name: "村田結生", group: "つばきファクトリー" },
  { name: "土居楓奏", group: "つばきファクトリー" },
  { name: "西村乙輝", group: "つばきファクトリー" },
  { name: "西田汐里", group: "BEYOOOOONDS" },
  { name: "江口紗耶", group: "BEYOOOOONDS" },
  { name: "高瀬くるみ", group: "BEYOOOOONDS" },
  { name: "前田こころ", group: "BEYOOOOONDS" },
  { name: "岡村美波", group: "BEYOOOOONDS" },
  { name: "清野桃々姫", group: "BEYOOOOONDS" },
  { name: "平井美葉", group: "BEYOOOOONDS" },
  { name: "小林萌花", group: "BEYOOOOONDS" },
  { name: "里吉うたの", group: "BEYOOOOONDS" },
  { name: "米村姫良々", group: "OCHA NORMA" },
  { name: "窪田七海", group: "OCHA NORMA" },
  { name: "西﨑美空", group: "OCHA NORMA" },
  { name: "筒井澪心", group: "OCHA NORMA" },
  { name: "斉藤円香", group: "OCHA NORMA" },
  { name: "北原もも", group: "OCHA NORMA" },
  { name: "中山夏月姫", group: "OCHA NORMA" },
  { name: "広本瑠璃", group: "OCHA NORMA" },
  { name: "橋田歩果", group: "ロージークロニクル" },
  { name: "吉田姫杷", group: "ロージークロニクル" },
  { name: "小野田華凜", group: "ロージークロニクル" },
  { name: "村越彩菜", group: "ロージークロニクル" },
  { name: "相馬優芽", group: "ロージークロニクル" },
  { name: "松原ユリヤ", group: "ロージークロニクル" },
  { name: "島川波菜", group: "ロージークロニクル" },
  { name: "上村麗菜", group: "ロージークロニクル" },
  { name: "植村葉純", group: "ロージークロニクル" },
];

/** src/data/groups.ts の HELLO_GROUPS の name と同じ並び。 */
export const CROSSWORD_GROUPS: readonly string[] = [
  "モーニング娘。'26",
  "アンジュルム",
  "Juice=Juice",
  "つばきファクトリー",
  "BEYOOOOONDS",
  "CHICA#TETSU",
  "雨ノ森 川海",
  "SeasoningS",
  "OCHA NORMA",
  "ロージークロニクル",
  "ハロプロ研修生",
];
